language: node_js
os:
 - linux
node_js:
  - "11.10"
  - "10.15"
  - "8.15"
  - "6.16"
before_install:
  - 'case "${TRAVIS_NODE_VERSION}" in 0.*) export NPM_CONFIG_STRICT_SSL=false ;; esac'
  - 'nvm install-latest-npm'
install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
script:
  - 'if [ -n "${PRETEST-}" ]; then npm run pretest ; fi'
  - 'if [ -n "${POSTTEST-}" ]; then npm run posttest ; fi'
  - 'if [ -n "${COVERAGE-}" ]; then npm run coverage ; fi'
  - 'if [ -n "${TEST-}" ]; then npm run tests-only ; fi'
sudo: false
env:
  - TEST=true
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true
    - node_js: "11.9"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.8"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.7"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.6"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.5"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.4"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.3"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.2"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.1"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "11.0"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.14"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.13"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.12"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.11"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.10"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.9"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.8"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.7"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.6"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.5"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.4"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.3"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.2"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.1"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.0"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.14"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.13"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.12"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.11"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.10"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.9"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.8"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.7"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.6"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.5"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.4"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.3"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.2"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.1"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "8.0"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.15"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.14"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.13"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.12"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.11"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.10"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.9"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.8"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.7"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.6"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.5"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.4"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.3"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.2"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.1"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "6.0"
      env: TEST=true ALLOW_FAILURE=true
  allow_failures:
    - os: osx
    - env: TEST=true ALLOW_FAILURE=true
